doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        charset: UTF8
        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '15'

        types:
            category_id: App\Vokabular\Api\Infrastructure\Persistence\Doctrine\Type\CategoryIdType
            word_id: App\Vokabular\Api\Infrastructure\Persistence\Doctrine\Type\WordIdType
            gender: App\Vokabular\Api\Infrastructure\Persistence\Doctrine\Type\GenderType
            level: App\Vokabular\Api\Infrastructure\Persistence\Doctrine\Type\LevelType
            user_id: App\Vokabular\Api\Infrastructure\Persistence\Doctrine\Type\UserIdType
            user_training_id: App\Vokabular\Api\Infrastructure\Persistence\Doctrine\Type\UserTrainingIdType
            email: App\Vokabular\Api\Infrastructure\Persistence\Doctrine\Type\EmailType
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: false
        mappings:
            category:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Vokabular/Api/Infrastructure/Persistence/Doctrine/Mapping/Categories'
                prefix: 'App\Vokabular\Api\Domain\Model\Categories'
                alias: category

            word:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Vokabular/Api/Infrastructure/Persistence/Doctrine/Mapping/Words'
                prefix: 'App\Vokabular\Api\Domain\Model\Words'
                alias: word

            user:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Vokabular/Api/Infrastructure/Persistence/Doctrine/Mapping/Users'
                prefix: 'App\Vokabular\Api\Domain\Model\Users'
                alias: user

            user_training:
                mapping: true
                type: yml
                dir: '%kernel.project_dir%/src/Vokabular/Api/Infrastructure/Persistence/Doctrine/Mapping/Users'
                prefix: 'App\Vokabular\Api\Domain\Model\Users'
                alias: user_training
#when@test:
#    doctrine:
#        dbal:
#            # "TEST_TOKEN" is typically set by ParaTest
#            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

#when@prod:
#    doctrine:
#        orm:
#            auto_generate_proxy_classes: false
#            proxy_dir: '%kernel.build_dir%/doctrine/orm/Proxies'
#            query_cache_driver:
#                type: pool
#                pool: doctrine.system_cache_pool
#            result_cache_driver:
#                type: pool
#                pool: doctrine.result_cache_pool
#
#    framework:
#        cache:
#            pools:
#                doctrine.result_cache_pool:
#                    adapter: cache.app
#                doctrine.system_cache_pool:
#                    adapter: cache.system
