twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/Vokabular/Frontend/Backoffice/Infrastructure/Templates': 'frontend_office'
        '%kernel.project_dir%/src/Vokabular/Frontend/Frontoffice/Infrastructure/Templates': 'frontend_front'

when@test:
    twig:
        strict_variables: true
