services:

  _instanceof:
      App\Vokabular\Frontend\Shared\Domain\Bus\Command\CommandHandler:
          tags: [ 'internal.command_handler' ]

      App\Vokabular\Frontend\Shared\Domain\Bus\Query\QueryHandler:
        tags: [ 'internal.query_handler' ]

  ###  Buses
  frontend.share.command.commandBus:
    class: App\Vokabular\Frontend\Shared\Infrastructure\Bus\Command\InMemoryCommandBus
    arguments: [!tagged internal.command_handler]


  frontend.share.query.queryBus:
    class: App\Vokabular\Frontend\Shared\Infrastructure\Bus\Query\InMemoryQueryBus
    arguments: [!tagged internal.query_handler]
